---
title: CME Problem Set 2
date: last-modified
author: Breno Nacif
format:
  pdf:
    code-fold: true
include-in-header:
  text: |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
execute: 
  fig-format: png
engine: julia
---

## Setup & Packages
First, we activate the project and load the necessary packages.

```{julia}
#| message: false
#| output: false

# activate local Project.toml to manage package versions
import Pkg
Pkg.activate(".")

# load packages
using Interpolations, DataInterpolations, Distributions, Random,
      DataFrames, Plots, PrettyTables, Roots, BenchmarkTools
```

# Question 1
## (a)
We want to guess the life expectancy at birth for someone born in 1996.
To do so, observe that life expectancy increases monotonically with time according to the observed data, so we should not consider a cubic spline. Since the problem is one dimensional, we choose the Pchip.
```{julia}
# define vectors 
years = [1940, 1950, 1960, 1970, 1980, 1991, 2000, 2010]
expectancy = [45.5, 48.0, 52.5, 57.6, 62.5, 66.9, 71.1, 74.4]

# interpolate
# FritschButlandMonotonicInterpolation() applies the Pchip interpolation according to Fritsch & Butland (1984)
pchip_interp_life_exp = interpolate(
    years, expectancy,
    FritschButlandMonotonicInterpolation()
)

guess_1996 = pchip_interp_life_exp(1996)
println("The best guess for life expectancy in 1996 is $(round(guess_1996, digits=2)) years.")
```

## (b)
Now we plot the series of life expectancy filling the missing years using the Pchip interpolation.

```{julia}
years_plot = 1940:1:2010

plot(years, expectancy, 
     seriestype=:scatter, 
     label="Data",
     ylabel="Life Expectancy at birth", 
     legend=:topleft)
plot!(years_plot, pchip_interp_life_exp.(years_plot), label="Pchip")
```


# Question 2
In this question, we interpolate the PDF of a Pareto distribution 
$$
f(x)
= \frac{\alpha x^{\alpha}_{m}}{x^{\alpha+1}}
$$

with parameters $x_m=1$ and $\alpha=10$.

## (a) and (b)
To start, we define the function with the correct parameters and draw the sample from $U (1, 5)$. We also define a grid of 10 points from 1 to 5 to create the vector $y$ of the function values at these points.
```{julia}
# Pareto Function
function pareto_pdf(x, alpha, x_m)
    return (alpha * x_m^alpha) / (x^(alpha + 1))
end

alpha_val = 10.0
x_m_val = 1.0

# create sample of 2500 trying points 
Random.seed!(1881)
x = sort!(rand(Uniform(1.0, 5.0), 2500))

# compute the true values for the trying points
println("Check the sample below.")
f_true_q2 = pareto_pdf.(x, alpha_val, x_m_val)
```

Now we approximate the function with the trying points ($x$). We define three interpolation methods to do that: linear interpolation, cubic spline and Pchip.

## (c) e (d)
```{julia}
# methods to loop
methods = [
    DataInterpolations.LinearInterpolation,
    DataInterpolations.CubicSpline,
    DataInterpolations.PCHIPInterpolation
]
method_names = ["Linear", "Cubic Spline", "PCHIP"]

# approximation
for n in [10, 15, 20, 30, 50]
    # create the grid
    grid_t = collect(range(1.0, 5.0, length=n))
    y = pareto_pdf.(grid_t, alpha_val, x_m_val)
    # start the empty df
    df_mse = DataFrame(Method = method_names, MSE = zeros(3), Average_Time_μs = zeros(Int, 3))
    
    for (idx, method) in enumerate(methods)
        times = zeros(1000)
        mse = 0.0
        
        for rep in 1:1000
            t = @elapsed begin
                interp = method(y, grid_t)
                f_hat = interp.(x)
                error = f_true_q2 .- f_hat
                mse = sum(error.^2) / length(error)
            end
            times[rep] = t
        end
        
        df_mse[idx, :MSE] = mse
        df_mse[idx, :Average_Time_μs] = trunc(Int, 1e6 * mean(times)) # time in μs
    end
    
    println("\n--- Pareto Linear Grid with n = $n ---")
    pretty_table(df_mse)
end
```

## (e)
Here we repeat items (b), (c) and (d) using a log-spaced grid. The idea is that a log-spaced grid means more density at the beginning of the interval ($x = 1$), where the distribution has the highest curvature. This way the interpolation algorithms should capture the true shape more accurately.

```{julia}
for n in [10, 15, 20, 30, 50]
    # create the grid
    grid_t_log = exp.(range(log(1.0), log(5.0), length=n))
    y_log = pareto_pdf.(grid_t_log, alpha_val, x_m_val)
    # start the empty df
    df_mse = DataFrame(Method = method_names, MSE = zeros(3), Average_Time_μs = zeros(Int, 3))
    
    for (idx, method) in enumerate(methods)
        times = zeros(1000)
        mse = 0.0
        
        for rep in 1:1000
            t = @elapsed begin
                interp = method(y_log, grid_t_log)
                f_hat = interp.(x)
                error = f_true_q2 .- f_hat
                mse = sum(error.^2) / length(error)
            end
            times[rep] = t
        end
        
        df_mse[idx, :MSE] = mse
        df_mse[idx, :Average_Time_μs] = trunc(Int, 1e6 * mean(times)) # time in μs
    end
    
    println("\n--- Pareto Log-spaced Grid with n = $n ---")
    pretty_table(df_mse)
end
```

## (f)

We know the pdf of a Pareto distribution is steep at $x = x_m = 1$, and has a flat tail afterwards. An evenly spaced grid places too few nodes in this high-curvature region, causing more interpolation errors. Switching to a log-spaced grid makes more points closer to $x=1$. This way, as we expected, MSE indeed reduces across methods. Comparing between methods, Pchip often performs well as it respects the monotonicity and prevents the splines from overshooting the fat tail. However, this results in higher average time compared to the other algorithms.


# Question 3
Now the function is
$$
g(x) = [1 + \exp(-\eta \log (\frac{x}{\xi}))]^{-1}
$$

where $\eta=5$, $\xi=500$ and $x \in [200,1000]$.

We repeat the loops from Question 2, only changing the function.
```{julia}
function logistic_func(x, eta, xi)
    return 1.0 / (1.0 + exp(-eta * log(x / xi)))
end

eta_val = 5.0
xi_val = 500.0

trying_points_q3 = sort!(rand(Uniform(200.0, 1000.0), 2500))
f_true_q3 = logistic_func.(trying_points_q3, eta_val, xi_val)

# linear grid
for n in [10, 15, 20, 30, 50]
    grid_t = collect(range(200.0, 1000.0, length=n))
    y = logistic_func.(grid_t, eta_val, xi_val)
    
    df_mse = DataFrame(Method = method_names, MSE = zeros(3), Average_Time_μs = zeros(Int, 3))
    
    for (idx, method) in enumerate(methods)
        times = zeros(1000)
        mse = 0.0
        for rep in 1:1000
            t = @elapsed begin
                interp = method(y, grid_t)
                f_hat = interp.(trying_points_q3)
                error = f_true_q3 .- f_hat
                mse = sum(error.^2) / length(error)
            end
            times[rep] = t
        end
        df_mse[idx, :MSE] = mse
        df_mse[idx, :Average_Time_μs] = trunc(Int, 1e6 * mean(times))
    end
    
    println("\n--- Logistic Linear Grid with n = $n ---")
    pretty_table(df_mse)
end

# log grid
for n in [10, 15, 20, 30, 50]
    grid_t_log = exp.(range(log(200.0), log(1000.0), length=n))
    y_log = logistic_func.(grid_t_log, eta_val, xi_val)
    
    df_mse = DataFrame(Method = method_names, MSE = zeros(3), Average_Time_μs = zeros(Int, 3))
    
    for (idx, method) in enumerate(methods)
        times = zeros(1000)
        mse = 0.0
        for rep in 1:1000
            t = @elapsed begin
                interp = method(y_log, grid_t_log)
                f_hat = interp.(trying_points_q3)
                error = f_true_q3 .- f_hat
                mse = sum(error.^2) / length(error)
            end
            times[rep] = t
        end
        df_mse[idx, :MSE] = mse
        df_mse[idx, :Average_Time_μs] = trunc(Int, 1e6 * mean(times))
    end
    
    println("\n--- Logistic Log-spaced Grid with n = $n ---")
    pretty_table(df_mse)
end
```

## (a)
Unlike the Pareto distribution where the log grid was universally better, the log-spaced grid here does not perform better than the linear grid. The Pareto function's curvature is concentrated at the beginning of the interval, making a log grid good. In this case, having more nodes at beginning of the interval does not perform well probably because the function is flat around $x=200$, leaving the critical regions of the function with undersampled.

## (b)
The function is S-shaped. Its highest curvature happen near the inflection point in the middle of the interval. Therefore, the best grid would be dense around the middle of the interval ($x \approx 500$) rather than at the tails.


# Question 4
In this last question we want to find the root of:
$$
f(x) = x^3 + 2x + 5
$$

## (a)

The first step is to bracket the root. To do so, we check the function evaluated at some values of $x$ and look for where it changes signs.

::: {.callout}
If we expand and try an analytical answer we have
$$
x^3 + 2x + 5 = 0 \Leftrightarrow x (x^2 + 2) = -5
$$

Since $(x^2 + 2) > 0$, the root $x$ must be strictly negative.
:::

```{julia}
# define function -  in this case it is just a polynomial
f_root(x) = x^3 + 2x + 5

# guess values
println("f(-3) = ", f_root(-3.0)) # -27 - 6 + 5 = -28
println("f(-2) = ", f_root(-2.0)) # -8 - 4 + 5 = -7
println("f(-1) = ", f_root(-1.0)) # -1 - 2 + 5 = 2

println("\nThe root is bracketed in the interval [-2.0, -1.0].")
```

## (b)

Now we implement a bisection using this interval. The tolerance for a root is $10^8$ and we choose a maximum of iterations of 500.
```{julia} 
function bisection_method(f, a, b; tol=1e-8, max_iter=100)
    # check if initial interval is valid
    if f(a) * f(b) > 0
        error("Function values at the interval endpoints must have opposite signs.")
    end
    # initial values
    iter = 0
    c = (a + b) / 2.0
    
    while abs(b - a) > tol && iter < max_iter
        c = (a + b) / 2.0
        if abs(f(c)) < tol
            return c, iter
        end
        if f(a) * f(c) < 0
            b = c
        else
            a = c
        end
        iter += 1
    end
    
    if iter == max_iter
        println("Warning: Reached max_iter without converging.")
    end
    return c, iter
end

root_val, iterations = bisection_method(f_root, -2.0, -1.0)
println("\nRoot found using bisection method: ", root_val)
println("Number of iterations required: ", iterations)
```

## (c)
To use the secant method, we also need two initial values $x_0$ and $x_1$, but not necessarily a bracket. Here we use the same as before for comparison of the algorithms.

```{julia}
function secant_method(f, x0, x1; tol=1e-8, max_iter=500)
    iter = 0
    # initial values
    while abs(x1 - x0) > tol && iter < max_iter
        f_x0 = f(x0)
        f_x1 = f(x1)
        
        # avoid division by close to zero if the derivative is flat
        if abs(f_x1 - f_x0) < 1e-14
            println("Warning: Function is too flat, denominator approaching zero.")
            break
        end
        
        # secant formula
        x_next = x1 - f_x1 * (x1 - x0) / (f_x1 - f_x0)
        
        # update
        x0 = x1
        x1 = x_next
        iter += 1
        
        # check tolerance
        if abs(f(x1)) < tol
            return x1, iter
        end
    end
    # check convergence
    if iter == max_iter
        println("Warning: Reached max_iter without converging.")
    end
    return x1, iter
end

root_val_secant, iter_secant = secant_method(f_root, -2.0, -1.0)
println("\nRoot found using the secant method: ", root_val_secant)
println("Number of iterations required: ", iter_secant)
```

Choosing between bisection and secant is a trade-off between reliability and speed. In the bisection, we find the root for sure (if the brecket is correct), but it might be slow. Here it takes four times the number of iterations compared to the secant. In contrast, the secant method uses the slope of secant lines to jump toward the root and doesn't require a bracket. However, there is a risk of no convergence if the function is flat at some point and the denominator is close to zero.

## (d)
For the Newton-Raphson method, we need the function and its derivative: 
$$
 f(x) = x^3 + 2x + 5 \quad \Rightarrow \quad f'(x) = 3x^2 + 2.
$$

The update rule is:
$x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}$

```{julia}
f_prime(x) = 3x^2 + 2.0

function newton_raphson(f, df, x0; tol=1e-8, max_iter=500)
    # initial values
    iter = 0
    x = x0
    
    while abs(f(x)) > tol && iter < max_iter
        f_val = f(x)
        df_val = df(x)
        
        # avoid division by close to zero if the derivative is flat
        if abs(df_val) < 1e-14
            println("Warning: Derivative is close to zero, stopping to prevent division by zero.")
            break
        end
        
        # Newton-Raphson formula
        x_next = x - (f_val / df_val)
        
        # check tolerance
        if abs(x_next - x) < tol
            x = x_next
            iter += 1
            break
        end
        
        x = x_next
        iter += 1
    end
    # check convergence
    if iter == max_iter
        println("Warning: Reached max_iter without converging.")
    end
    
    return x, iter
end

# We only need one initial guess for Newton-Raphson
root_val_nr, iter_nr = newton_raphson(f_root, f_prime, -2.0)
println("\nRoot found using the Newton-Raphson method: ", root_val_nr)
println("Number of iterations required: ", iter_nr)
```

When comparing the three methods, there is a clear trade-off between convergence speed and the certainty of finding the root. The Newton-Raphson method is the fastest if the initial guess is not too close to the root. It also requires an analytical derivative that might not be easy to compute. The secant method converges fast without needing a derivative, but it can also diverge. In contrast, the bisection method is the slowest but the most reliable with a valid initial bracket.